# configs/polyp_alb352_cos.yaml

optim:
  # Optimization / schedule
  optimizer: AdamW
  cos_lr: true
  lr0: 0.004       # CLI --lr0 still overrides
  lrf: 0.01
  momentum: 0.94
  weight_decay: 0.0007
  warmup_epochs: 3.0
  warmup_momentum: 0.80
  warmup_bias_lr: 0.10
  patience: 40
  cache: true

  # Polyp-safe built-in YOLO aug toggles (keep these mild; Albumentations will do the heavy lifting)
  mosaic: 0.0
  mixup: 0.0
  copy_paste: 0.0
  single_cls: true

albumentations:
  # ←— your exact pipeline pasted verbatim
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    p: 1.0
    transforms:
      - __class_fullname__: albumentations.augmentations.crops.transforms.RandomCrop
        height: 352
        width: 352
        p: 1.0
      - __class_fullname__: albumentations.augmentations.geometric.rotate.Rotate
        limit: [0, 90]
        border_mode: 0
        interpolation: 1
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.HorizontalFlip
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.VerticalFlip
        p: 0.5
      - __class_fullname__: albumentations.core.composition.OneOf
        p: 0.3
        transforms:
          - __class_fullname__: albumentations.augmentations.transforms.GaussNoise
            var_limit: [0.0, 150.0]
            mean: 0
            per_channel: true
            p: 1.0
          - __class_fullname__: albumentations.augmentations.transforms.GaussNoise
            var_limit: [10.0, 50.0]
            mean: 0
            p: 1.0
      - __class_fullname__: albumentations.core.composition.OneOf
        p: 0.3
        transforms:
          - __class_fullname__: albumentations.augmentations.geometric.transforms.ShiftScaleRotate
            shift_limit: 0.0
            scale_limit: 0.2
            rotate_limit: 45
            border_mode: 0
            interpolation: 1
            p: 1.0
          - __class_fullname__: albumentations.augmentations.transforms.RandomBrightnessContrast
            brightness_limit: 0.1
            contrast_limit: 0.1
            p: 1.0
      - __class_fullname__: albumentations.core.composition.OneOf
        p: 0.3
        transforms:
          - __class_fullname__: albumentations.augmentations.transforms.MotionBlur
            blur_limit: [3, 7]
            p: 1.0
          - __class_fullname__: albumentations.augmentations.transforms.MedianBlur
            blur_limit: 3
            p: 1.0
      - __class_fullname__: albumentations.core.composition.OneOf
        p: 0.3
        transforms:
          - __class_fullname__: albumentations.augmentations.dropout.mask_dropout.MaskDropout
            max_objects: 1
            fill_value: 0
            mask_fill_value: 0
            p: 1.0
          - __class_fullname__: albumentations.augmentations.transforms.GaussNoise
            var_limit: [10.0, 50.0]
            mean: 0
            p: 1.0
      - __class_fullname__: albumentations.augmentations.transforms.ColorJitter
        brightness: 0.2
        contrast: 0.2
        saturation: 0.2
        hue: 0.2
        p: 0.3
